name: Build and Test Rust App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cache Cargo dependencies
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Build the Rust project
      - name: Build
        run: cargo build --verbose

      # Run tests
      - name: Run Tests
        run: cargo test --verbose
        
      - name: Basic test
        run: |
          nohup ./target/debug/c2pa-check > app.log 2>&1 &
          while ! curl -s http://localhost:8000/healthz/live > /dev/null; do sleep 1; done
          ./scripts/test.sh
          TEST_EXIT_CODE=$?
          kill %1 # Kill background process
          exit $TEST_EXIT_CODE
          